services:
  api:
  build: 
    context: frontend
    dockerfile: dockerfile
  container_name: stranger_things
  environment:
    SPRING_PROFILES_ACTIVE: local
  ports:
    - "8082:8080"

  db:
    image: mysql:8.0
    container_name: BBDD
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./sql/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
    